ALTER TABLE shipments
    ADD COLUMN type   ENUM('MEMBERSHIP', 'STANDALONE') NOT NULL DEFAULT 'STANDALONE',
    ADD COLUMN status ENUM('PROPOSED', 'CONFIRMED', 'CANCELLED') NOT NULL DEFAULT 'CONFIRMED';

UPDATE shipments SET type = 'STANDALONE' WHERE tiendanube_order_id IS NOT NULL;
UPDATE shipments SET type = 'MEMBERSHIP' WHERE tiendanube_order_id IS NULL;
